spring:

  application:
    name: my-bnl-application

  datasource:
    url: jdbc:mysql://localhost:3306/app_bnl_spring_boot
    username: root
    password: BERENICEroberto*04

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect

jwt:
  secret: QzU2eXpQbW56N2JDUHlWRmtHbWhnQTRmZWR6YmhrVjE=
  expiration: 86400000


